### ISSUE TITLE
Question: Wii support

### ISSUE THREAD

**Issue by NiQ1** [Wack0/maciNTosh#26]
If I understand correctly the Wii uses more or less the same chip, and even parts of the project have been ported over from the Homebrew Channel.

Do you think it might be possible to use BootMii to boot Windows NT on the Wii?

Thanks.

**Comment by Wack0** [comment]
This port ended up using the things I learned from my attempt to port NT to the Wii, which I sidelined because of GPU memory corruption on real hardware and that powerpc mac laptops were cheaper than a usb gecko.

**Comment by Wack0** [comment]
I was told the most likely cause of the issue on real hardware: apparently sync instruction needs to be before any read/write to EFB. Which means EFB can't be used directly, and video miniport driver will need to be refactored because of that.

I'll eventually get around to it, but I'd need to refactor basically everything such that MSR_LE is properly used.

**Comment by heathercat123** [comment]
Shouldn't this get "re-closed" as done instead of not planned since [wack0 'got around to it'](https://github.com/Wack0/entii-for-workcubes)?
